In [2]:
# https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc/code
# 开始是手动敲，后面工作量太大是看着复制的
import numpy as np
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']


In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [10]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [13]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.0443919  0.97791552 0.25167426]
  [0.23420595 0.29183167 0.47854433]
  [0.85888981 0.88966975 0.86780415]]

 [[0.80229985 0.11730376 0.08426149]
  [0.35666762 0.53716881 0.91372474]
  [0.4549601  0.99645022 0.46669996]]

 [[0.64730798 0.88590636 0.39822774]
  [0.97447251 0.553004   0.59752906]
  [0.15342684 0.01307539 0.82477098]]]


In [15]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0005833936772985382 0.9923857050532267


In [16]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.514575390250376


In [20]:
Z = np.ones((10,10))  # 创建一个二维数组，其中边界值为1，其余值为0
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
Z = np.ones((5,5))  # 对于一个存在在数组，如何添加一个用0填充的边界
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [25]:
print(0 * np.nan)

nan


In [26]:
print(np.nan == np.nan)

False


In [27]:
print(np.inf > np.nan)

False


In [28]:
print(np.nan - np.nan)

nan


In [29]:
print(0.3 == 3 * 0.1)

False


In [32]:
Z = np.diag(1+np.arange(4),k=-1)  # 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [35]:
Z = np.zeros((8,8),dtype=int)  # 创建一个8x8 的矩阵，并且设置成棋盘样式
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [36]:
print(np.unravel_index(100,(6,7,8)))  # 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么

(1, 5, 4)


In [39]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))  # 用tile函数去创建一个 8x8的棋盘样式矩阵(比[1::2,::2]这个方法好)
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.71929506 0.59219625 0.51759364 0.73012895 0.18290953]
 [0.16759976 1.         0.7024619  0.         0.71918069]
 [0.0919684  0.84308051 0.26336094 0.08620359 0.12146289]
 [0.82152903 0.77485629 0.84971009 0.35244236 0.00821325]
 [0.00373437 0.71756437 0.10074314 0.85929714 0.30123106]]


In [41]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
color  # 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [42]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [44]:
print(sum(range(5),-1))  # 调用的是Python的原生sum接口

9


In [45]:
from numpy import *
print(sum(range(5),-1))  # 调用的是numpy的sum接口

10


In [46]:
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256], dtype=int32)

In [47]:
2 << Z >> 2  # >> 和 <<都是位运算，对二进制数进行移位操作

array([0, 1, 2, 4, 8], dtype=int32)

In [49]:
Z <- Z   # legal

array([False, False, False, False, False])

In [50]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [51]:
Z/1/1

array([0., 1., 2., 3., 4.])

In [52]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
print(np.array(0) / np.array(0))

nan


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [54]:
print(np.array(0) // np.array(0))

0


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [55]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [56]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 10.   2.   7.   4. -10. -10. -10.  -4. -10.   7.]


In [57]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))  # 找到两个数组中的共同元素

[3 6 9]


In [60]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


In [61]:
# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:
    with np.errstate(divide='ignore'):
        Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-61-ded05fdd9153>, line 5)

In [62]:
np.sqrt(-1) == np.emath.sqrt(-1)  # False

False

In [63]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-05-11
Today is 2019-05-12
Tomorrow is 2019-05-13


In [64]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [65]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)  # 直接在位计算(A+B)\*(-A/2)(不建立副本)
 # 提示: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)

array([3., 3., 3.])

In [66]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [67]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [68]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [70]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)

[2. 0. 6. 2. 0. 4. 3. 5. 3. 7.]


In [71]:
print (np.floor(Z))

[2. 0. 6. 2. 0. 4. 3. 5. 3. 7.]


In [72]:
print (np.ceil(Z)-1)

[2. 0. 6. 2. 0. 4. 3. 5. 3. 7.]


In [73]:
print (Z.astype(int))

[2 0 6 2 0 4 3 5 3 7]


In [74]:
print (np.trunc(Z))

[2. 0. 6. 2. 0. 4. 3. 5. 3. 7.]


In [78]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [81]:
def generate():
    for x in range(10):
         yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [83]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [84]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.17052696 0.21192604 0.25189516 0.27190406 0.43744238 0.46924778
 0.58437731 0.81112026 0.85214416 0.93364265]


In [85]:
# 对于一个小数组，如何用比 np.sum更快的方式对其求和
Z = np.arange(10)
np.add.reduce(Z)

45

In [86]:
# 对于两个随机数组A和B，检查它们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [87]:
equal = np.array_equal(A,B)
print(equal)

False


In [88]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [89]:
# 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.50467279 0.2126286  1.03222972 0.97211626 0.05034007 0.54498071
 0.46769285 0.57803933 0.81182179 1.20519279]
[1.47023012 0.50486256 0.68901073 0.8770055  1.35958662 0.78551539
 1.40922349 0.13949538 1.44787971 0.86586317]


In [91]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

[0.59569751 0.29283334 1.         0.47782378 0.07299075 0.01790681
 0.72161954 0.50372419 0.68767384 0.7118966 ]


In [92]:
# 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [93]:
# 给定两个数组X和Y，构造Cauchy矩阵C 
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [94]:
# 打印每个numpy标量类型的最小值和最大值
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [95]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [96]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

97


In [97]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [98]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.42780848 0.19610187 0.4444768  0.44747516 0.49578708
  0.33105727 0.30718384 0.26252618 0.37014442]
 [0.42780848 0.         0.35823261 0.20507405 0.47613003 0.89867696
  0.75599368 0.35079687 0.4465002  0.25966334]
 [0.19610187 0.35823261 0.         0.46469707 0.5762513  0.67339147
  0.48773318 0.41792832 0.42102072 0.1958326 ]
 [0.4444768  0.20507405 0.46469707 0.         0.29596163 0.83861948
  0.73599342 0.22016891 0.33832846 0.4374837 ]
 [0.44747516 0.47613003 0.5762513  0.29596163 0.         0.65251674
  0.61799178 0.1597209  0.19548537 0.64151973]
 [0.49578708 0.89867696 0.67339147 0.83861948 0.65251674 0.
  0.20242971 0.62360212 0.50518421 0.86247937]
 [0.33105727 0.75599368 0.48773318 0.73599342 0.61799178 0.20242971
  0.         0.54111334 0.43482798 0.68182696]
 [0.30718384 0.35079687 0.41792832 0.22016891 0.1597209  0.62360212
  0.54111334 0.         0.11909694 0.4856996 ]
 [0.26252618 0.4465002  0.42102072 0.33832846 0.19548537 0.50518421
  0.43482798 0.11909

In [99]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [100]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [101]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [102]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [103]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.21518447 -0.11370067 -0.27402645  0.33745575 -0.02513591  0.22343893
  -0.01098882  0.31237772 -0.29008231 -0.3745227 ]
 [ 0.47909075  0.51431565 -0.47560429  0.22025368  0.08995115  0.23160586
  -0.43871861 -0.46019409 -0.3444088   0.18370872]
 [ 0.11017161 -0.25262528  0.19994621  0.22950267  0.22588042  0.07373974
  -0.17479643 -0.30372785  0.1613481  -0.26943919]
 [-0.34825152 -0.06999428 -0.05539241  0.56198456  0.15978766 -0.31344723
  -0.25052401  0.00668979 -0.0628909   0.37203833]
 [ 0.18061828  0.17999673 -0.29802098  0.10474497 -0.36111125 -0.2031629
   0.34796013  0.32281922 -0.29253416  0.01868997]]


In [104]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[4 4 8]
 [7 0 5]
 [2 5 8]]
[[7 0 5]
 [4 4 8]
 [2 5 8]]


In [105]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [106]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5076517169735


In [108]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [110]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [111]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 1. 2. 4. 1. 5. 5. 3. 3.]


In [112]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [113]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [115]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[57 55 52 58]
 [56 53 45 70]
 [63 52 81 51]]


In [116]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.37675474 0.49572436 0.56682145 0.50037918 0.42665942 0.46192784
 0.49922947 0.34496907 0.59731127 0.65981322]


In [117]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([1.33056636, 1.19187493, 1.32830356, 1.12199597, 2.00016927])

In [118]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [119]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [120]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [121]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 1, 29) ( 1, 44) ( 5, 35) ( 5, 80) ( 7, 25) ( 7, 75) (12, 34) (12, 58)
 (14, 62) (14, 86) (21, 56) (21, 62) (24, 52) (24, 64) (25, 75) (29, 44)
 (34, 58) (35, 80) (37, 46) (37, 49) (46, 49) (50, 69) (50, 83) (52, 64)
 (56, 62) (62, 86) (69, 83) (80, 87) (80, 93) (87, 93)]


In [122]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [123]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [124]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [125]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [126]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 7.34505927  7.23291138  7.92150161 10.15545585  1.92979876  3.04165276
 11.02781549  6.84399835  6.63936521  4.03240703]


In [127]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.06075518  6.66007678  4.25396778  2.80614355  5.81849542  8.36805222
   9.52248144  4.52065152  9.89622615  5.38144131]
 [15.20085927  4.86554752  9.81448641 12.75615181 11.51526291  8.05790166
   7.87257342  2.40882787  1.99632046  3.35296297]
 [11.34064415  5.85495594  6.54439538  9.24344979  8.29270335  4.41292893
   4.63349117  3.46121797  4.16535896  2.15176303]
 [ 1.57846989 12.99403561  7.13874259  4.90659271  0.96495261  9.93171135
   4.70522254 10.80738994 14.98523363  1.47012538]
 [13.61398034  1.76964143 10.97654378 13.50273585  8.79286643  8.52310709
   5.16695712  0.65781022  0.37023345  0.19570416]
 [ 8.07303794  9.62144568  1.68046586  4.43818154  6.73360209  0.31447914
   3.04069203  7.2781966   8.72599408  3.68950926]
 [ 0.4330964   9.33514916  3.76038268  1.759608    1.35163316  6.96358461
   5.06435235  7.13306079 11.21117697  1.10856866]
 [ 1.86691032  5.48787061  0.5191387   2.37080083  0.73149458  2.96549979
   4.4124447   3.25139732  6.88838257  3.23416849]


In [128]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[7 5 0 6 7 3 7 6 2 3]
 [3 4 7 2 6 5 7 6 8 6]
 [7 3 6 5 8 4 2 8 7 8]
 [4 4 6 1 4 8 2 3 7 5]
 [6 5 7 5 3 2 1 0 6 9]
 [7 9 1 8 6 4 9 6 4 0]
 [1 7 9 0 8 7 3 3 3 9]
 [3 4 8 4 9 5 2 4 5 5]
 [4 2 4 3 9 0 2 5 5 6]
 [0 2 3 1 5 3 6 3 9 8]]
[[0 0 0 0 0]
 [0 7 5 0 6]
 [0 3 4 7 2]
 [0 7 3 6 5]
 [0 4 4 6 1]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [129]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [130]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [131]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

4


In [132]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 1 3]
   [2 1 0]
   [3 1 4]]

  [[1 3 3]
   [1 0 0]
   [1 4 1]]

  [[3 3 1]
   [0 0 1]
   [4 1 2]]

  [[3 1 1]
   [0 1 1]
   [1 2 4]]

  [[1 1 2]
   [1 1 1]
   [2 4 4]]

  [[1 2 0]
   [1 1 2]
   [4 4 3]]

  [[2 0 1]
   [1 2 2]
   [4 3 1]]

  [[0 1 1]
   [2 2 4]
   [3 1 2]]]


 [[[2 1 0]
   [3 1 4]
   [1 4 3]]

  [[1 0 0]
   [1 4 1]
   [4 3 3]]

  [[0 0 1]
   [4 1 2]
   [3 3 4]]

  [[0 1 1]
   [1 2 4]
   [3 4 2]]

  [[1 1 1]
   [2 4 4]
   [4 2 4]]

  [[1 1 2]
   [4 4 3]
   [2 4 2]]

  [[1 2 2]
   [4 3 1]
   [4 2 0]]

  [[2 2 4]
   [3 1 2]
   [2 0 4]]]


 [[[3 1 4]
   [1 4 3]
   [2 2 2]]

  [[1 4 1]
   [4 3 3]
   [2 2 1]]

  [[4 1 2]
   [3 3 4]
   [2 1 1]]

  [[1 2 4]
   [3 4 2]
   [1 1 3]]

  [[2 4 4]
   [4 2 4]
   [1 3 0]]

  [[4 4 3]
   [2 4 2]
   [3 0 3]]

  [[4 3 1]
   [4 2 0]
   [0 3 3]]

  [[3 1 2]
   [2 0 4]
   [3 3 4]]]


 [[[1 4 3]
   [2 2 2]
   [1 4 0]]

  [[4 3 3]
   [2 2 1]
   [4 0 0]]

  [[3 3 4]
   [2 1 1]
   [0 0 4]]

  [[3 4 2]
   [1 1 3]
   [0 4 3]]

  [[4 2 4]
   

In [133]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 6  1  7  3  6]
 [ 1  8  3 13  8]
 [ 7  3  7 42  5]
 [ 3 13 42  6  7]
 [ 6  8  5  7  6]]


In [135]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [136]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [137]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [138]:
print (Z[np.argpartition(-Z,n)[:n]])

[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
   0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0
   0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0
   1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1
   1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
   1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
   0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 

In [139]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [140]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [142]:
x = np.random.rand()
np.power(x,3)

0.22531566507442985

In [143]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 3 4 5 6]


In [156]:
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[1 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


In [146]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [147]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


In [148]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
6.023742702593449


In [149]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.10462219 0.47028939 0.03214045 0.08297277 0.86908405 0.2118758
 0.192139   0.15325888 0.75429191 0.15634891]


In [150]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
3.027023341008742


In [151]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[0.10462219 0.30649637 0.13253321 0.49870831 0.46091042 0.27851605
  0.12449666 0.19738069 0.42504656 0.08914438]
 [0.16053275 0.47028939 0.20335954 0.76522025 0.70722301 0.42735626
  0.19102823 0.30286181 0.65219333 0.13678354]
 [0.02537179 0.07432802 0.03214045 0.12094108 0.11177477 0.06754255
  0.03019152 0.04786653 0.10307747 0.02161828]
 [0.01740655 0.05099344 0.02205026 0.08297277 0.07668414 0.04633821
  0.02071318 0.03283928 0.07071727 0.01483143]
 [0.19727364 0.5779238  0.24990213 0.94035504 0.86908405 0.52516463
  0.23474857 0.37217732 0.80145982 0.16808897]
 [0.07958935 0.2331613  0.10082213 0.37938289 0.35062887 0.2118758
  0.09470848 0.15015362 0.32334611 0.0678149 ]
 [0.1614662  0.47302396 0.20454201 0.76966974 0.71133526 0.42984119
  0.192139   0.30462284 0.65598561 0.13757888]
 [0.0812353  0.2379832  0.10290718 0.38722874 0.35788006 0.21625751
  0.0966671  0.15325888 0.33003309 0.06921735]
 [0.18566359 0.54391154 0.23519477 0.88501279 0.81793628 0.49425738
  0.220

In [153]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [154]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [155]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.07884647  0.28616242]
